name: Telegram Notification

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Ручной запуск

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Событие в GitHub!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref }}
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.head_commit.message }}
